### ISSUE TITLE
idInjection not working

### ISSUE THREAD

**Issue by alexyma** [strongloop/loopback-connector-mssql#1]
I set idInjection option to false and the mssql still creates an id PK field.

**Comment by idosh** [comment]
I can't set a model id manually even after setting idInjection to false.
After looking inside the mssql connector source, I found that idInjection is ignored and it deletes the primary key by default.

**Comment by raymondfeng** [comment]
@idosh Can you provide a test case to reproduce the problem? A link to your github repo is ideal.

**Comment by idosh** [comment]
I'm working on a closed source project so I can't link my repo here.
Here is my model definition:

```
{
    "name": "Facebook",
    "plural": "Facebook",
    "properties": {
        "id": {
            "type": "Number",
            "id": true,
            "required": true,
            "generated": false,
            "idInjection": false,
            "precision": 20,
            "scale": 0,
            "mssql": {
                "dataType": "bigint",
                "dataPrecision": 20,
                "dataScale": 0
            }
        },
        "token": {
            "type": "String",
            "required": true,
            "mssql": {
                "dataType": "text"
            }
        }
    },
    "relations": {
        "user": {
            "type": "belongsTo",
            "model": "User",
            "foreignKey": "userId"
        }
    },
    "acls": [
        {
            "principalType": "ROLE",
            "principalId": "$everyone",
            "permission": "DENY"
        },
        {
            "principalType": "ROLE",
            "principalId": "$everyone",
            "permission": "ALLOW",
            "property": "create"
        }
    ]
}
```

As you can see, I'm defining a model without id injection but still my id field is ignored.
I look into the mssql connector source code and found these two lines in the `buildInsert` method:

```
delete data[modelPKID];
delete data.id;
```

**Comment by sochka** [comment]
I believe this problem this exists. My schema:
```
{
  "name": "accessToken",
  "plural": "accessTokens",
  "base": "AccessToken",
  "idInjection": "false",
  "options": {
    "idInjections": "false"
  },
  "properties": {
    "id": {
      "type": "string",
      "id": true,
      "generated": false,
      "mssql": {
        "dataType": "nvarchar(255)"
      }
    }
  },
  "validations": [],
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userId"
    }
  },
  "acls": [],
  "methods": {}
}

```

Running `app.dataSources.db.autoupdate()` results  with the following DDL for me:

```
CREATE TABLE AccessToken
(
    id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    ttl INT,
    created DATETIME,
    userId INT
);```

**Comment by kanchantripathi** [comment]
Hi,

I am also facing the same issue. below is my schema. 

{
  "name": "ctp-assignment-sysn",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
   "assignment_sysn_id": {"type": "number", "id": true, "generated": true},

    "student_id": {
      "type": "number",
      "required": true
    },
    "teacher_id": {
      "type": "number",
      "required": true
    },
    "assignment_sysn_time": {
      "type": "date",
      "required": true
    },
    "assignment_master_id": {
      "type": "number",
      "required": true
    },
    "assignment_sysn_status": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

when I am checking my model in browser it looks like :

{
  "assignment_sysn_id": 0,
  "student_id": 0,
  "teacher_id": 0,
  "assignment_sysn_time": "2016-09-01",
  "assignment_master_id": 0,
  "assignment_sysn_status": "string",
  **"id": 0**
}

**"id": 0** filed is getting added automatically. I do not want this id field to be added. Please let me know the solution.

**Comment by shaheero** [comment]
Got the same problem. "idInjection": false, but still it gets added. Any solution?

**Comment by mulleady1** [comment]
For anyone who has an id getting added even after setting `{ "idInjection": false }`, what worked for me was to set `{ "id": <number> }` on my composite key properties. For example,
```
"properties": {
  "someFk1": {
    "type": "number",
    "id": 1
  },
  "someFk2": {
    "type": "number",
    "id": 2
  }
}
```
