### ISSUE TITLE
Models generated use actual Column name, not valid camel cased Class properties

### ISSUE THREAD

**Issue by Jeff-Lewis** [strongloop/loopback-connector-mssql#12]
Before I assume this is an issue, is Loopback intending that Models/objects in javascript have camel cased properties and these properties are translated to their corresponding columns names  provided by the model's definition schema? If so, I don't believe this work properly for the mssql connector.

Most if not all of mssql.js code gets the actual column names from the Model's property keys. See the mssql [buildInsert() method](https://github.com/strongloop/loopback-connector-mssql/blob/master/lib/mssql.js#L375-397) as it uses the model's js property names, which happen to be the same as what slc loopback:model generate.

**If I generate a model using slc command line ( slc loopback:model), I can make a model with these SQL valid column names but they are not valid js object property names, mainly because of the dashes.**

``` json
{
  "name": "testColumnNames",
  "base": "Model",
  "properties": {
    "My_First_Col": {
      "type": "string"
    },
    "the-Second_cOlumn": {
      "type": "string"
    },
    "theThirdColumn": {
      "type": "string"
    },
    "Only-Dash": {
      "type": "string"
    },
    "Only_Underscore": {
      "type": "string"
    },
    "ALLUPPER": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

I was about to paste in what this generated Schema using Discovery but discoverModelProperties() on this table returns an empty array...

Anyway, I also noticed in the mssql tests, the column names for any CRUD are all camelcase "acceptable" names. I suggest trying the same tests with the valid SQL column names that would be different when translated into camel case or class-ified names.

**Comment by agnes512** [comment]
please check [#3343](https://github.com/strongloop/loopback-next/issues/3343)
