### ISSUE TITLE
autoupdate does not alter table to add indexes

### ISSUE THREAD

**Issue by ataft** [strongloop/loopback-connector-mssql#121]
I can see that this is a work in progress, as the "showIndexes" function is labeled TODO. SQL Server (and Oracle) does not support "ALTER TABLE [table] ADD INDEX" syntax, so the "alterTable" function should use the same logic as the create does in the "singleIndexSettingsSQL" function.

**Comment by robbievandam** [comment]
Any update on this?
Currently the autoupdate is a no-go because of this unfortunately.
