### ISSUE TITLE
Option to set dateFormat

### ISSUE THREAD

**Issue by ariskemper** [strongloop/loopback-connector-mssql#125]
Currently its not possible to change dateFormat via options, which could introduce errors like
RequestError: The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.
Tedious is forcing mdy date format. This will be fixed in new release of tedious and afterwards in node-mssql.

**Comment by dhmlau** [comment]
When installing `loopback-connector-mssql@2.9.0`, it's installing `mssql@3.3.0` and `tedious@1.14.0`.  Are those the versions you're referring to?  If not, could you please specify them.  Thanks.

**Comment by dhmlau** [comment]
@ariskemper, is this good to close?

**Comment by dhmlau** [comment]
@ariskemper, please respond by next Friday (April 28) so that we can have closure on this.  If not, I'd close it by that day.  Thanks.

**Comment by dhmlau** [comment]
@ariskemper, we believe this problem has been resolved.  If you are still running into problems, feel free to leave a comment and I will reopen the issue.
