### ISSUE TITLE
No support for REGEXP

### ISSUE THREAD

**Issue by peebles** [strongloop/loopback-connector-mssql#136]
The loopback doc does not suggest that regexp support in where clauses is database connector specific.  It seems to suggest that regexp will work whatever database connector is in use, however when I used regexp in a where clause I get "Microsoft SQL Server does not support the regular expression operator" message from the server to stdout, and this response from the request: "Incorrect syntax near 'REGEXP'."

**Comment by MantasR** [comment]
Same issue here...

Was always using MYSQL  or postgres and just now had to use MS SQL...
