### ISSUE TITLE
any charge if using mssql connector

### ISSUE THREAD

**Issue by reidlai** [strongloop/loopback-connector-mssql#164]
I found the license is not MIT.  Does it mean I need to pay when I use this connector in production?

**Comment by dhmlau** [comment]
@reidlai, you're right.  This connector is under IBM International Program License Agreement (IPLA).  
See https://github.com/strongloop/loopback-connector-mssql/blob/master/LICENSE.md for details. 

If you'd like to purchase the license, it would be `API Connect for Node.js` license.  You can also see [this](https://www.ibm.com/support/knowledgecenter/en/SSMNED_5.0.0/com.ibm.apic.overview.doc/overview_rapic_offerings.html).

**Comment by dhmlau** [comment]
@reidlai , we believe we've answered your question.  Closing this issue now.  If you have further question regarding this topic, feel free to reopen.  Thanks.
