### ISSUE TITLE
INFORMATION_SCHEMA vs information_schema

### ISSUE THREAD

**Issue by edokan** [strongloop/loopback-connector-mssql#17]
Hi,

In Turkish, lowercase I is not i, so on discovery.js, queries using "information_schema" fails. I tried changing to INFORMATION_SCHEMA, and it seems working.

Please see "Turkey Test"

Sincerely

**Comment by emrahcetiner** [comment]
up

**Comment by raymondfeng** [comment]
See https://msdn.microsoft.com/en-us/library/aa290124(v=vs.71).aspx. 

Can you test if your SQL server installation is case sensitive?

If you can contribute a PR to use the correct case, we'll be happy to review.

**Comment by emrahcetiner** [comment]
"Turkish_CI_AS" defined as Server Collation.
CI = Case Insensitive

Problem isnt CI or CS. Problem is "turkish" definition. In turkish, lowercase I is not i.
i -> İ
ı -> I

**Comment by ssh24** [comment]
Fixed in PR #123
