### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by joostdebruijn** [strongloop/loopback-connector-mssql#170]
I did not have an concrete issue at this moment, but will there be a new release soon? There are a lot of interesting commits since the last release six months ago (especially the upgrade of the mssql dependency from 3.x to 4.x), which I would like to use. Let me know if I can do something to help. :smiley:

**Comment by dhmlau** [comment]
@joostdebruijn , thanks for the reminder.  `3.1.0` has just released. 
Closing the issue now.  Thanks.
