### ISSUE TITLE
loopback-connector-mssql windows authentication

### ISSUE THREAD

**Issue by Unarine** [strongloop/loopback-connector-mssql#177]
Hi,
Does loopback allow for windows authentication when using the mssql connector? If so, how can I achieve this?

**Comment by jacko** [comment]
The same issue, is there any solution ?

**Comment by Unarine** [comment]
So far none that I've seen

**Comment by jannyHou** [comment]
@Unarine loopback-connector-mssql is using nodejs driver `require('mssql')`, but the windows authentication is only supported in another driver `require('mssql/msnodesqlv8')`
see https://github.com/tediousjs/node-mssql#microsoft--contributors-node-v8-driver-for-nodejs-for-sql-server

I am not sure what is the compatibility between those two drivers...and how much effort we need to do a driver switch.

**Comment by jannyHou** [comment]
See issue https://github.com/tediousjs/tedious/issues/246#issuecomment-131417555 connecting using windows authentication can work by modifying the datasources.json within the LoopBack application to include the "domain" attribute.  Something like this:
"myds": {
    "connector": "mssql",
    "host": "company.com",
    "database": "demo",
    "domain": "DOMAIN_NAME_CAPITALIZED_AND_NOT_FQDM",
    "server": "servername",
    "username": "user",
    "password": "password"
  }

---

I verified it works.

I created an loopback 3 app with template "Note", which comes with a default "Note" model. Then created a mssql datasource with the following configure(please note the "domain" property is provided), and attached the "Note" model to that datasource:

"mssql": {
  "host": "127.0.0.1",
  "port": 1434,
  "domain": "LOCALHOST",
  "database": "mydatabase",
  "password": "mypassword",
  "user": "myusername",
}

Migrate the model and create two sample instances from the explorer.
Switch to the mssql terminal and select all instances from the table "Note", you can see the new instances are added to the database.
![screen shot 2018-07-18 at 12 35 45 pm](https://user-images.githubusercontent.com/12554153/43080041-bfe2781a-8e5c-11e8-866c-4077e5df369b.png)

I am closing this issue. Feel free to reopen it if you still have questions. Thanks

**Comment by Aditya-Thakur** [comment]
I have tried all the things still getting the error:....
hiding the username for obvious reasons
"error": {
    "statusCode": 500,
    "name": "ConnectionError",
    "message": "Login failed for user '*******\\Aditya*****'.",
    "code": "ELOGIN",
    "originalError": {
      "message": "Login failed for user '*******\\Aditya*****''.",
      "code": "ELOGIN"
    },

here's the code in datasources.json
 "SQLEXPRESS": {
    "host": "localhost",
    "port": 1433,
    "database": "EBS_QA",
    "password": "*******",
    "name": "SQLEXPRESS",
    "domain":"******",
    "user": "aditya****",
    "driver":"mssql/msnodesqlv8",
    "connector": "loopback-connector-mssql",
    "lazyConnect": true,
    "options": {
      "encrypt": false
  }  
I don't understand what else I am missing... The username and password I am using is my windows credentials.
