### ISSUE TITLE
Autoupdate error: index or statistics already exists on table 

### ISSUE THREAD

**Issue by Narrator** [strongloop/loopback-connector-mssql#180]
I get the following message whenever I run autoupdate:

`"error":{"message":"The operation failed because an index or statistics with name 'principalId_NONCLUSTERED_ASC_idx' already exists on table 'dbo.RoleMapping'.","stack":"RequestError: The operation failed because an index or statistics with name 'principalId_NONCLUSTERED_ASC_idx' already exists on table 'dbo.RoleMapping'
`
The table name doesn't matter, cause the error is thrown on different tables  every time. The first run is fine, but whenever I kill the app and restart it, this error is thrown.

Here's  the code I'm using in `boot/auto-update.js`

```
'use strict';

module.exports = function(app, done) {
  var logger = require('../../server/logger');
  var log = logger.child({module: 'auto-update'});

  var mssql = app.dataSources.mssql;

  mssql.autoupdate(function(err) {
    if (err) {
      log.error({error: err}, 'Error autoupdating DB');
      return done(err);
    }
    log.info('Database updation complete.');
    done();
  });
};
```

**Comment by javiersuazomatus** [comment]
I have the same problem. Could someone solve it?

my model definition:

```json
{
  "name": "OIDCModel",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "key": {
      "type": "string",
      "required": true
    },
    "value": {
      "type": "string",
      "required": true,
      "mssql": {
        "dataType": "text"
      }
    },
    "grantId": {
      "type": "string"
    },
    "expiresAt": {
      "type": "date",
      "required": true
    },
    "consumed": {
      "type": "boolean",
      "default": false
    }
  },
  "indexes": {
    "name_key": {
      "columns": "name,key"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**Comment by pumppi** [comment]
I have the same issue? How you solved?

**Comment by ataft** [comment]
This is due to a bug in migration.js where it uses async.each instead of async.eachSeries. async.each has no order, so the index create was happening before the drop. I've created this PR to fix the issue:
https://github.com/strongloop/loopback-connector-mssql/pull/228
