### ISSUE TITLE
loopback 4 model options not working for mssql 

### ISSUE THREAD

**Issue by phiricharles101** [strongloop/loopback-connector-mssql#197]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by phiricharles101** [comment]
Hi,

I am trying to connect to a mssql db and specify the table name. I have tried the below and still not working. 

@model({
    name: 'VehicleModel',
        options: {
            mssql: {
                schema: 'dbo',
                table: 'Vehicles_VehicleRecord'
            }
        }

})
export class VehicleModel extends Entity {
	@property({
		type: 'number',
		id: true,
		required: true
	})
	id: number;

	@property({
		type: 'string',
		required: true
	})
	name: string;

	constructor(data?: Partial<VehicleModel>) {
		super(data);
	}
}

ERROR: 

Invalid object name 'dbo.VehicleModel'.

**Comment by dhmlau** [comment]
@phiricharles101 , it should be something like:
```
@model({
  settings: {
    postgresql: {
      table: 'customer',
    },
  },
})
export class Customer2 extends Entity {
```

For details, please see details in this GitHub issue: https://github.com/strongloop/loopback-next/issues/2134, and continue discussion there.

**Comment by phiricharles101** [comment]
@dhmlau  
Thank you so much, 
I was also missing @loopback/repository-json-schema in the package.json

**Comment by dhmlau** [comment]
@phiricharles101 , is this issue good to close then? Thanks.

**Comment by phiricharles101** [comment]
Yes it is. Thanks
