### ISSUE TITLE
Incorrect Table Relations Discovery

### ISSUE THREAD

**Issue by axadn** [strongloop/loopback-connector-mssql#199]
Table discovery methods currently report incorrect information for foreign key constraints. 
This causes trouble using methods like datasource.discoverForeignKeys, datasource.discoverAndBuildModels, etc. 

The problem is that the table with the foreign key and the table with the primary key are reported to be this same table.

**Comment by dhmlau** [comment]
Marking it as `community contribution` because @axadn has created PR #201 .

**Comment by dhmlau** [comment]
not stale.
