### ISSUE TITLE
executeSql should return mssql results

### ISSUE THREAD

**Issue by ataft** [strongloop/loopback-connector-mssql#229]
As you can see [here](https://github.com/strongloop/loopback-connector-mssql/blob/master/lib/mssql.js#L128), `executeSql()` only returns `data.recordset`. This effectively neuters the connector, not allowing it to return the richer functionality of the mssql connector, namely things like `rowsAffected`.

Would there be interest in allowing an option for `returnRawData`? I'd make the PR and clearly it wouldn't affect any users. It would be very simple, like this:
```
    debug('Result: %j %j', err, data);
    if (data&&!options.returnRawData) {
      data = data.recordset;
    }
    callback && callback(err, data);
```

This would save me, and perhaps other Loopback users, from having to use separate ORM's like TypeORM for SQL querying.

**Comment by dhmlau** [comment]
@ataft, thanks for the suggestion. Your proposal sounds reasonable to me. It's important for us to keep the backward compatibility. @jannyHou, what do you think? Thanks.

**Comment by jannyHou** [comment]
@ataft Thank you for the suggestion and investigation made. 👍 

> I'd make the PR and clearly it wouldn't affect any users.

And we really appreciate your help on the the code contribution 👍, will review it when ready. 
Changing the returned data of `executeSQL` would affect all CRUD queries, if you only want to configure the result of a native query, I think you need to make the `option` turned off by default. And better disable it for the built-in CRUD queries.

I checked the sqlServer query runner in TypeORM, and find they also returns the `result.recordset` by default, sometimes returns the `result.affectedRows`. Just curious...could you explain more about when the raw data is needed?

**Comment by ataft** [comment]
Maybe the term "raw data" is confusing. I mean return whatever object the mssql library returns. The use case is to get `rowsAffected` or any of the other results:
https://github.com/tediousjs/node-mssql#execute-procedure-callback

Yes, it would clearly be off by default.
