### ISSUE TITLE
Why does toDatabase() convert dates to UTC?

### ISSUE THREAD

**Issue by Jeff-Lewis** [strongloop/loopback-connector-mssql#24]
I know it's best practice to store dates as UTC but often developers are working with existing systems that do not. I'm not sure why the connector should force this on the developer as the default. 

Most DB access layers using MSSQL that I've used do not do this conversion automatically. I think it should either leave the date alone or maybe make it an option to convert to UTC that could be 'true' by default if you don't want to make a breaking change.

Also, it appears fromDatabase() does not convert back. It really can't because not all MSSQL date types support timezones.

**Comment by Jeff-Lewis** [comment]
It appears tedious has a [config option 'useUTC'](https://github.com/pekim/tedious/blob/1ad5e697d2d55410063f2948039180dc882b08fd/src/connection.coffee#L276) which controls this behavior. I would make sense that we expose this as well.

**Comment by ylandau** [comment]
in mysql it was fixed. see: https://github.com/strongloop/loopback-connector-mysql/issues/149,
can it be fixed in mssql?

thanks!

**Comment by llhilton** [comment]
I've been wrestling with this very issue. Sad to see how long it's been a problem. I've got a working version of a fix on my local that just involves having TZ and USE_UTC present in process.env. Wondering if a PR would be of interest. I didn't see anything in the tests that specifically deals with this issue. (Though I wasn't able to get the Docker container running so I couldn't see if this change actually breaks any tests.)
