### ISSUE TITLE
Support read-only Views as models

### ISSUE THREAD

**Issue by Jeff-Lewis** [strongloop/loopback-connector-mssql#26]
Does LB plan to support read-only views in MsSQL where there might not be a primary key? 

Integrating existing 3rd party systems into the SL micro-services architecture is very valuable. Currently, I assume we could add (hack) new wrapper views with a fake Primary Keys which does something like `select someKey,* from view` in order to comply.

@raymondfeng What are you thoughts?

**Comment by raymondfeng** [comment]
Interesting use case. If it happens, some of the methods won't be allowed, such as `findById`. Only `find`, `findOne` and `count`. I assume it should be functional today if you supply an explicit `order` property for the `filter` arg on `find`.

**Comment by OwenBrotherwood** [comment]
So far, I have find and count working on a Read-Only table (not view). I have to check if the discover data model (via arc) actually defined a Primary Key.

Please note that the order property is necessary at least for limit:
https://github.com/strongloop/loopback-connector-mssql/issues/40

I created issue 40 before reading this seemingly unrelated issue.

**Comment by OwenBrotherwood** [comment]
As @raymondfeng noted: Interesting Use Case.
Do we define the Use Case as one has to create code that can interact with a 3rd Party Database Table/View and the use of http://docs.strongloop.com/display/public/LB/Discovering+models+from+relational+databases ?
There could be several gotcha's that one may need to be aware of.
FYI
My next task is to discover models from relation databases where the tables are related.

**Comment by ganipadela** [comment]
Any update on this ?
