### ISSUE TITLE
slc debug with mssql connector

### ISSUE THREAD

**Issue by idosh** [strongloop/loopback-connector-mssql#30]
I can't manage to debug loopback application which uses the loopback-connector-mssql.
It always throws timeout error.

```
Connection fails:  { [ConnectionError: Failed to connect to xxxxxx:1433 in 15000ms]
  name: 'ConnectionError',
  message: 'Failed to connect to xxxxxx:1433 in 15000ms',
  code: 'ETIMEOUT' } 
It will be retried for the next request.
```

**Comment by raymondfeng** [comment]
You can set the `requestTimeout` in your data source config. See descriptions at https://github.com/patriksimek/node-mssql#basic-configuration-is-same-for-all-drivers.

**Comment by idosh** [comment]
Great, it works!
