### ISSUE TITLE
Connection With Keep-Alive

### ISSUE THREAD

**Issue by idosh** [strongloop/loopback-connector-mssql#33]
The load balancing policy on Azure is to disconnect connections that are idle for 30 minutes or more.
Is there any way to connect to Azure SQL with keep-alive connection?

**Comment by raymondfeng** [comment]
The driver we use under the hook seems to have supported `keep-alive` already. See https://github.com/ravensteel/tedious/commit/5aee02800b942407dfeebdc13afda2560e525ccd.

**Comment by idosh** [comment]
Great thanks!

**Comment by idosh** [comment]
After investigating a little bit, I found the [guidelines for Azure SQL](https://msdn.microsoft.com/en-us/library/ee336245.aspx)
Basically it says that after 30 min of idleness the connection is closed.
Is there any way to use  connection pooling instead of one global connection?
