### ISSUE TITLE
Fault-Tolerance Support

### ISSUE THREAD

**Issue by dashby3000** [strongloop/loopback-connector-mssql#36]
Regarding SQL Server connection params for fault-tolerance, we need support for `Data Source=Server_A;Failover Partner=Server_B`

Customer scheduled to go to prodcution in 4 weeks.  This is a blocker.

PLATAPI-383

**Comment by chandadharap** [comment]
MSSQL

**Comment by chandadharap** [comment]
The driver does not seem to support fault-tolerance out of box. We will need to implement this code ourself. This seems a project by itself. (if we need to achieve parity with other solutions).

**Comment by chandadharap** [comment]
Al, Raymond and Dennis discussed. This is more scope than a "fix". Dennis to follow up for a Professional Services possibility.

**Comment by superkhau** [comment]
Closing as abandoned. If you are still interested in working on this in the future, just ping and we can reopen it then.
