### ISSUE TITLE
Default Data Type Is Used For Foreign Keys With Custom Data Type On Auto-Update/Migrate

### ISSUE THREAD

**Issue by idoshamun** [strongloop/loopback-connector-mssql#38]
Let's say I define a user model which its id is a Number ad set custom data type as bigint.
When I define another model which belongs to user the foreign key will be an int not a bigint.

**Comment by dhmlau** [comment]
@idoshamun , sorry to take so long to respond.  Since it's been 2 years that this issue is created, are you still running into this problem?  If so, I can start the investigation.  If not, I'd like to close this.  Thanks.

**Comment by idoshamun** [comment]
You can close, thanks
