### ISSUE TITLE
limit and order

### ISSUE THREAD

**Issue by OwenBrotherwood** [strongloop/loopback-connector-mssql#40]
An observation that may be a documentation issue.
With the loopback-connector-mssql, it is possible to define a limit: <some nr>.
This results in "bad sql".

With a console.log(command) in ../node_modules/loopback-connector-mssql/node_modules/mssql/lib/tedious.js, one observes a ROW_NUMBER() OVER(null).

Adding a order:column gives a OVER(ORDER BY [column]), and one is happy again.

As stated, this could be a general documentation problem for all loopback-connector-somedb

Br Owen

Edit:
Summary: if you have to discover a model from a database, and use slc arc and there is already an id column in the database, make sure you understand the "is id" flag that arc shows when presenting the result of the discovery ...

**Comment by raymondfeng** [comment]
What's your model definition? By default, it should use the `id` property for ordering.

**Comment by OwenBrotherwood** [comment]
I think I am finding the "problem" : the model is a discovered model by arc on a Read Only Database.
I will investigate if arc found a primary key.

**Comment by OwenBrotherwood** [comment]
OK: Not too sure but ...
Requirement, discover model and make some magic code: I used arc and it created a good enough model and I note that idInjection: false and an id is present as:

```
    "id": {
      "type": "String",
      "required": false,
      "length": 60,
      "precision": null,
      "scale": null,
      "mssql": {
        "columnName": "ID",
        "dataType": "varchar",
        "dataLength": 60,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "YES"
      },
      "_selectable": true
    },
```
Investigating ID, I find that ID is present in the MSSQL Table, value null for all values.

A conclusion? beats me just now so I am googling and found https://github.com/strongloop/loopback-connector-mssql/pull/29 which may have no relation to the problem.
It seems that id is necessary, for problem free operation but there is an id (ID) already defined.

**Comment by OwenBrotherwood** [comment]
Removed id (ID) from the model, regenerated lb-services.js and removed the order:column and ...
Everything worked:)
Sooo...
I have a gap in my understanding of the magic of id but have also learned that if id(ID) is in the database I want to discover a model for, I may have issues and would need to understand the magic.
I wonder if there is a document that I should read (or should be made)

**Comment by OwenBrotherwood** [comment]
slc arc revisited.

When using slc arc to discover the model from a database, one can select a column as "is id"
I chose a column, and selected "is id" and repeated a regeneration of lb-services.js _without_ deleting a referance to the id(MSSQL ID).
Everything worked:) Well done whoever did the "is id".

**Comment by crandmck** [comment]
If there is a specific issue with the docs (something wrong, missing, or unclear), please let me know.  
I can't seem to figure it out from the above...

**Comment by OwenBrotherwood** [comment]
@crandmck  
The Use Case was I had to use MSSQL tables from a third party system (ie, I needed to consume another systems data). Basically, with very little doc from the third party system, I had to discover the model and use the model for a MEAN app.

One crash course in a slc arc discover model later, I have the following:

- if the model that is discovered has an 'id', the code generates an error, as per first post. The reason for the error was that the third party system had an ID but with all values as null giving a  ROW_NUMBER() OVER(null) . I suggest a test that throws if the OVER is null

- I have to check if the documentation for discovery of a model clearly shows the importance of the "is id". As a beginner, I missed the importance in my crash course

FYI as strongloop seems to be working for me, I will be continueing my journey with a MSSQL instance that is "mine" and will be using it for further tests: using a third party system as a first project was an interesting learning process but having one's own instance allows for better tests and understanding.

**Comment by crandmck** [comment]
@OwenBrotherwood Thanks for the suggestions.  I added a note to several of the above articles highlighting the ID property with a cross-reference.

**Comment by OwenBrotherwood** [comment]
@crandmck 
From gitter.im:
How do you get models to have an auto incrementing PK? Omit id? Use _id or something?
hmm, looks like I need to use “generated”: true?


http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-IDproperties
- I couldn't quickly answer the question.
