### ISSUE TITLE
GeoPoint inconsistency?

### ISSUE THREAD

**Issue by dbarbeau** [strongloop/loopback-connector-mssql#41]
Hello,

I'm starting to use this connector in preparation of a deployment. I'm migrating from using the memory connector. I have a model with a `gps:"geopoint"` property. When querying an instance of that model the memory connector properly returns an object of similar to {lat:number, lng:number}, while the mssql connector returns a string (resulting in a cascade of errors). Also, when inspecting the database, the type of that property is "varchar(255)", couldn't "geometry" be better suited?

The fix is easy on my side, but since it may affect more people I thought I could at least file a bug report even if it ends up not being one :)

Daniel

**Comment by juancaacuna** [comment]
Hi @dbarbeau ! How did you exactly solve this?

Thanks!
