### ISSUE TITLE
Windows SSO Authentication

### ISSUE THREAD

**Issue by bandra** [strongloop/loopback-connector-mssql#42]
Does the connector have support for using Windows SSO for authentication to SQL Server using Windows Authentication? Or is the only supported method using SQLServer auth with username/password?

**Comment by mattwoolnough** [comment]
+1!

**Comment by iguyking** [comment]
+1

**Comment by digitalsadhu** [comment]
I did some digging on this a while back, IIRC, the underlying mssql module doesn't really support it. In theory it does if the correct driver is used (not the default) but that came with limitations such as being stuck on node 0.10 and requiring native bindings and such.

**Comment by jrutter** [comment]
+1 - Im currently having trouble with this as I need to connect under a domain, but nodejs is complaining about the '/' backslash in my username. Has anyone found a way to get around this?

**Comment by johnsoftek** [comment]
Two back-slashes?

**Comment by creativekinetix** [comment]
mssql should now support his using msnodsqlv8 driver on windows. Are there any plans for adding this as an option in the near future?

**Comment by creativekinetix** [comment]
tedious seems to have just merged in Windows-only support for this as well.

**Comment by robbievandam** [comment]
Any news/update on this would be appreciated.

**Comment by dhmlau** [comment]
Please see comment in here: https://github.com/strongloop/loopback-connector-mssql/issues/177#issuecomment-407062308
