### ISSUE TITLE
Connet to instance 

### ISSUE THREAD

**Issue by rbonillajr** [strongloop/loopback-connector-mssql#46]
How to connet instance? for example SEVER\SQLEXPRESS

 config = {
    user: 'user',
    password: 'pass',
    host: 'server',
    database: 'dbname',
    supportsOffSetFetch: Math.random() > 0.5
  }

**Comment by margagn** [comment]
I have the same question...

**Comment by dhmlau** [comment]
@rbonillajr , sorry to take so long to respond.  Is your question still valid?  If so, please elaborate more on what you're trying to do.  If the question is no longer valid, I can close this issue.  Thanks.

**Comment by dhmlau** [comment]
Due to inactivity.  Closing this issue.
@rbonillajr , if you still encounter this issue, feel free to reopen with the additional information requested above.  Thanks!
