### ISSUE TITLE
connectors:mssql licensing missing or invalid

### ISSUE THREAD

**Issue by makersu** [strongloop/loopback-connector-mssql#47]
When I "slc run", it showed:
```
## connectors:mssql licensing missing or invalid. Please verify your licenses in the Licenses page by running StrongLoop Arc by typing "slc arc --licenses" . If you have questions about your license or StrongLoop licensing please contact sales@strongloop.com.
```

But when I "slc arc --licenses", I can not find the licenses page.(on logout button?)

When query http://0.0.0.0:3000/api/Users:
```
{
  "error": {
    "name": "RequestError",
    "status": 500,
    "message": "Invalid object name 'dbo.ACL'.",
    "code": "EREQUEST",
    "number": 208,
    "lineNumber": 1,
    "state": 1,
    "class": 16,
    "serverName": "WIN-SV2EV1V9NJ4",
    "procName": "",
    "precedingErrors": [],
...
```

Please hint.Thank you very much.

**Comment by fuadhasni** [comment]
+1

**Comment by superkhau** [comment]
@crandmck Probably need some docs to guide the users.

**Comment by crandmck** [comment]
The docs already cover this in some detail: https://docs.strongloop.com/display/SL/Managing+your+licenses.

However, when you run `slc arc --licenses` you should see the licenses page straight away (see screenshot below), so you shouldn't really need much guidance... Perhaps I'm misunderstanding the issue?

![arc licenses](https://cloud.githubusercontent.com/assets/2925364/10296872/adca11e8-6b81-11e5-9fab-5d9444dd1c6f.png)

**Comment by crandmck** [comment]
@superkhau can we close this?  I don't think we can clarify it any more.

**Comment by superkhau** [comment]
@crandmck Close it.

@makersu @fuadhasni Please comment again if you are still running into issues and we'll repon this issue.

**Comment by margagn** [comment]
It looks like most of the connectors require an annual subscription. You should make that clear on the Strongloop and Loopback (http://loopback.io) website. If I had known that earlier, I wouldn't have spent time learning this framework. I am going to have to use another framework for my project.

**Comment by crandmck** [comment]
@margagn Only Oracle, MS SQL Server, and SOAP connectors require a paid license.  All the others listed on https://docs.strongloop.com/display/LB/Database+connectors are free / open source.
