### ISSUE TITLE
Inserting Arabic into Database is not Working?

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [strongloop/loopback-connector-mssql#51]
I have tried to insert Arabic into one of my columns (`nvarchar`) but always getting ????? .. Any clue please?

**Comment by superkhau** [comment]
What database/conector are you using? Is your database set up to recognize UTF-8?

**Comment by ahmed-abdulmoniem** [comment]
My database is SQL Server using this connector `loopback-connector-mssql`.

How to setup the database to recognize UTF-8?

**Comment by superkhau** [comment]
>How to setup the database to recognize UTF-8?

This is not LoopBack specific, you will need to Google how to do it for your specific database. If you need direct support, we offer subscription plans. See https://strongloop.com/node-js/subscription-plans/. Closing for now, feel free to reopen once you confirm it's an actual LoopBack issue.

**Comment by ahmed-abdulmoniem** [comment]
So you think it is not loopback issue? I wasted 3 hours until now on how to configure the SQL Server to support UTF8 but it doesn't support that. I think the connector should convert data to something appropriate to be saved correctly in Arabic in database.

**Comment by ahmed-abdulmoniem** [comment]
@superkhau @raymondfeng 
I have changed this line

https://github.com/strongloop/loopback-connector-mssql/blob/master/lib/mssql.js#L266

to:

`return "N'" + val + "'";`

This adds support to unicode.

**Comment by raymondfeng** [comment]
Based on https://support.microsoft.com/en-us/kb/239530, your proposed change looks good to me. Do you want to submit a patch?

**Comment by ahmed-abdulmoniem** [comment]
Yeah sure

**Comment by ahmed-abdulmoniem** [comment]
@raymondfeng Here it is https://github.com/strongloop/loopback-connector-mssql/pull/52

**Comment by superkhau** [comment]
>So you think it is not loopback issue?

I wasn't sure if it was yet, but I wanted you to confirm the database side before reopening the issue, which @raymondfeng has already done.

>I wasted 3 hours until now on how to configure the SQL Server to support UTF8 but it doesn't support that. I think the connector should convert data to something appropriate to be saved correctly in Arabic in database.

Thanks for researching it and coming to the conclusion that it was Loopback related. As we look at a lot of issues, we appreciate that issues are confirmed before reporting. I will take a look at the patch and get it merged ASAP.

**Comment by ahmed-abdulmoniem** [comment]
@superkhau Thank you :)

**Comment by superkhau** [comment]
Resolved via https://github.com/strongloop/loopback-connector-mssql/pull/52.
