### ISSUE TITLE
number data type should have a float or decimal definition in db

### ISSUE THREAD

**Issue by jaideepdas** [strongloop/loopback-connector-mssql#54]
If I define number in the model for a field type, in the db definition its becoming int, shouldn't it be float or decimal as loopback uses number for float and decimal https://docs.strongloop.com/display/public/LB/LoopBack+types

**Comment by superkhau** [comment]
JavaScript only supports the Number type.

@raymondfeng Thoughts? ^

**Comment by jaideepdas** [comment]
But then at db level this is causing issue by creating INT when FLOAT is needed.

**Comment by xinbenlv** [comment]
+1

**Comment by xinbenlv** [comment]
Please open this
