### ISSUE TITLE
SQL Server Express

### ISSUE THREAD

**Issue by sochka** [strongloop/loopback-connector-mssql#66]
Hi, is it possible to connect to SQL Server Express? Usually, it doesn't have a port, username and password since it was created for development purposes.

**Comment by superkhau** [comment]
We only officially support SQL Server. However, you are free to try with that connector https://docs.strongloop.com/display/public/LB/SQL+Server+connector. Basically leave the username, port nad password field empty. Let me know how it goes. ;)

**Comment by sochka** [comment]
Hi, it crashes with the following trace:
```
 [22:22:19] e/projects/shopimate-api [master]> node .
Starting app...
## connectors:mssql is licensed from 2016-01-16T23:27:13.860Z to 2016-02-15T23:27:13.860Z.
Connection fails:  { [ConnectionError: Failed to connect to undefined:1433 - connect ECONNREFUSED 127.0.0.1:1433]
  name: 'ConnectionError',
  message: 'Failed to connect to undefined:1433 - connect ECONNREFUSED 127.0.0.1:1433',
  code: 'ESOCKET' }
It will be retried for the next request.

events.js:141
      throw er; // Unhandled 'error' event
      ^
 ConnectionError: Failed to connect to undefined:1433 - connect ECONNREFUSED 127.0.0.1:1433
    at Connection.<anonymous> (E:\Projects\shopimate-api\node_modules\mssql\lib\tedious.js:358:25)
    at Connection.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection.socketError (E:\Projects\shopimate-api\node_modules\tedious\lib\connection.js:571:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickDomainCallback (node.js:429:17)
```

With this config:

```
  "db": {
    "name": "db",
    "connector": "mssql",
    "database": "shopimate"
  },
}
```

**Comment by sochka** [comment]
Correcting myself: I'm actually using SQL Server Express LocalDB, not SQL Server Express

**Comment by superkhau** [comment]
@sochka Thanks for testing. No we do not support those two specifically. You are free to try to create one or search on https://www.npmjs.com/search?q=loopback-connector for one. Would be a good community project. ;)

**Comment by acclaimuser** [comment]
Hi there, I am trying to connect SQL server which is running in my local windows machine. when i am trying to connect using the loopback connector; it still looking up in the port 1433 and errored with the same message as mentioned above.

Even i tried in API connect portal and ended up with same error message.

Where am I missing? thanks.

**Comment by acclaimuser** [comment]
Okay, I am able to figure out this. Need to enable TCP/IP protocol for the SQL server instance to get it connected. able to discover the tables to generate models now.
