### ISSUE TITLE
Cannot create SQL Server table with a character key

### ISSUE THREAD

**Issue by johnsoftek** [strongloop/loopback-connector-mssql#7]
I cannot create a SQL Server table with a character key using automigrate. It works fine with a MySQL datasource. LoopBack 2.0.2, loopback-connector-mssql 1.1.0

```
 "idInjection": false,
  "properties": {
    "code": {
      "type": "String",
      "id": true,
      "length": 20,
      "nullable": false,
      "generated": false,
      "mysql": {
        "dataType": "varchar",
        "dataLength": 20
      },
      "mssql": {
        "dataType": "varchar",
        "dataLength": 20
      }
    },
```

I have tried several variations on the above without success.

The automigrate code in mssql.js calls the propertiesSQL function. The column identified as the key is always generated as an int identity column.

```
MsSQL.prototype.propertiesSQL = function (model) {
  // debugger;
  var self = this;
  var objModel = this._models[model];
  var modelPKID = this.idName(model);

  var sql = ["[" + modelPKID + "] [int] IDENTITY(1,1) NOT NULL"];
  Object.keys(objModel.properties).forEach(function (prop) {
    console.log(prop)
    if (prop === modelPKID) {
      return;
    }
```

**Comment by f0ysal** [comment]
@johnsoftek @raymondfeng @aams I am still having similar issues is this fixed?

I am trying to save/update a model with some attribute changes where I do not have any ID property. But when I am debugging the datasource-juggler and getting a SQL like this:

INSERT INTO [dbo].[LastUsedID] ([LastIDUsed])
VALUES (59);
SELECT IDENT_CURRENT('[dbo].[LastUsedID]') AS pkid;

Is it natural I think I should get an update query?

**Comment by sochka** [comment]
The AccessToken table (which was created automatically through  this code)

```
app.dataSources.db.autoupdate(err => {
  if (err) throw err;
  console.log('Models autoupdated');
  cb();
});
```

has the following schema:

```

CREATE TABLE [dbo].[AccessToken] (
    [id]      UNIQUEIDENTIFIER NOT NULL,
    [ttl]     INT              NULL,
    [created] DATETIME         NULL,
    [userId]  INT              NULL
);
```

And this doesn't work with inserts due to the fact that IDs are actually strings! Have I done something wrong or that's the issue everybody had?

**Comment by peebles** [comment]
Show stopper for me as well.  I think it is not uncommon now-a-days to use UID strings as primary ID keys, so that client side users of the database cannot "predict" other user ids (for example) based on their user id.  If I am user ID 4, then there might be a user with an ID of 5 and I can try to probe that.  I built my whole application using:

```javascript
{
   "id": {
      "type": "string",
      "id": true,
      "defaultFn": "shortid"
  }
}
```

and tested and deployed with MySQL, Postgres and Mongo ... then a client comes along needing MSSQL and it doesn't work.
