### ISSUE TITLE
Syntax for Indexes Model JSON Does Not Match Documentation

### ISSUE THREAD

**Issue by dknapp47** [strongloop/loopback-connector-mssql#74]
Based on the documentation at the bottom of this page:

https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Indexes

I believe that I should be able to do this:

  "indexes": {
    "ERPIDandLTPID": {
      "entityReportingPeriodId": 1,
      "lowerTierPartnerId": 1
    }
  }

But after studying the source, I need to do this:

  "indexes":{
    "blah": {
      "columns": "entityReportingPeriodId,lowerTierPartnerId"
    }
  }

I'm fine with either syntax but it would help if the code and docs matched.

**Comment by jrvboesch** [comment]
if I want them to be unique?

**Comment by jrvboesch** [comment]
I need to make an index and specify to be unique, how can I do it?
