### ISSUE TITLE
Regression in 2.7.0: Float Column Type is Rounded to Integer

### ISSUE THREAD

**Issue by dknapp47** [strongloop/loopback-connector-mssql#77]
I have this model JSON:

"properties": {
    "percentage": {
      "type": "number",
      "required": true,
      "mssql": {
        "dataType": "float"
      }
    }
  }

In 2.6.0 (and possibly earlier), the value is correctly written to the database table.

In 2.70, the value is rounded to the closest integer.

**Comment by raymondfeng** [comment]
Fixed by loopback-connector-mssql@2.7.1
