### ISSUE TITLE
Security hole - auth token is simple integer

### ISSUE THREAD

**Issue by aams** [strongloop/loopback-connector-mssql#9]
The AccessToken table is created with an auto-increment integer. So session authorization tokens are 1, 2, 3 etc.

Any one can use /explorer or curl to try tokens from 1 upwards until a valid token is found.

**Comment by CodeConcepts** [comment]
Hi, I was just wondering if this issue has been resolved? It seems to be quite a serious problem.

**Comment by sochka** [comment]
I think this was fixed.

**Comment by superkhau** [comment]
Fixed via #23
