### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by Amir-61** [strongloop/loopback-connector-mssql#90]
It seems [this test](https://github.com/strongloop/loopback-datasource-juggler/blob/f1ed1ee023d06edf9acd1ad3c8b56a22834abe63/test/manipulation.test.js#L730-L758) has been failing since July 23rd:

The error message:

```
Conversion failed when converting from a character string to uniqueidentifier.
```

The test case has been passing and it still passes on all other connectors except `loopback-connector-mssql`

@superkhau @0candy @loay The test was added on July 7th and it was passing up to July 23rd; do you know why it started failing? We may need to skip this test for now if we cannot figure out the reason soon. Something is wrong just with `loopback-connector-mssql`

CC: @bajtos @raymondfeng

![screen shot 2016-07-27 at 12 28 11 pm](https://cloud.githubusercontent.com/assets/10672146/17183626/6538e388-53f6-11e6-90be-24663fe4e354.png)

**Comment by dhmlau** [comment]
seems like the tests are passing.  can we close this? @loay

**Comment by dhmlau** [comment]
Closing this because all tests in CI for this repo pass.  If there's any failure, feel free to open a new issue.  Thanks.
